# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06739c1bfbb528df839b4dad4152b31c731dacb1a7b9a330383142be01bde27dfc90e2b6e9e9e6b15e081dcdc4e812d10d83851531a1cfd5437accadd3aac4a2

test:
  secret_key_base: c105964e96ae0297f5747be053ffbc1f9049975fbf7e48f6fa0a43070cbb83126e93df6289de28c62272f40e63e65cad9ea8ea71a74919dd1758827b9f9c02fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
